#!/bin/sh

set -exu

basedir=$(dirname $0)
exec ansible-playbook \
    --vault-password-file=$basedir/vault-passwd \
    --inventory-file=$basedir/hosts \
    --verbose \
    "$@" \
    $basedir/site.yml
